# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2e3d1c33b18b59404121e18643fc01d4b2f6085508ed7f888b33964418e3690821bbf887384f494328126643101f3db468c257809dbdc6bad06d822e3fe1a49

test:
  secret_key_base: 9e80d44731e536b56af76392aa9d03ab1d762377001864006e4fe88a2dd75e2aa992c3846f9d2cd8607332677d58bd9c026fb03b6a0edc28fd87c39da1e86ffc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
